### ISSUE TITLE
Can't able to Access Keychain After revoke distribution certificate

### ISSUE THREAD

**Issue by vnavink** [pkrll/Keychain#2]
I am working in project which is already in Appstore submitted by different developer. Now I am trying to submit updated version of the app with different version and build number. I can't able to access previously stored keychain values. I am using Keychain Pods to store and retrieve data

Here is the steps I did

Revoked the old Distribution certificate created by another person and created a new one with my machine.
Regenerated Provisioning Profile which is used by previous developers
Code signed and submitted to App Store
Downloading old build from App Store
Installing the updated build from test flight
Now I can't able to access keychain values already stored.
Now what can I do to retrieve the old keychain value? I have also checked the team ID for Keychain group access it is same as old one. Is there any way I can retrieve the old keychain values

**Comment by pkrll** [comment]
Are you sure it is the same provisioning profile?

Open the old and the new provisioning profiles in a text editor and compare them.

[https://stackoverflow.com/questions/13313715/does-renewing-a-provisioning-profile-affect-keychain-access-when-i-submit-an-app](url)
